spring:
  application:
    name: product-management
server:
  port: 8084


## Feign Clients
#stores:
#  client:
#    url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000